import * as vm from 'node:vm';

export interface ExecuteResult {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  result: any;
  error?: string;
  logs?: string[];
}

/**
 * A custom implementation of the Code Mode Executor interface
 * utilizing the native Node.js 'vm' module to evaluate generated code.
 */
export const localNodeExecutor = {
  async execute(
    code: string,
    // eslint-disable-next-line @typescript-eslint/no-unsafe-function-type
    contextFns: Record<string, Function>
  ): Promise<ExecuteResult> {
    const sandbox = {
      codemode: contextFns,
      console: console,
      Promise: Promise,
    };

    vm.createContext(sandbox);

    // Evaluate the async arrow function generated by the LLM
    // Wrapping the code in parenthesis and immediately invoking it ensures
    // the returned promise can be awaited by the host process.
    const script = new vm.Script(`(${code})()`);

    try {
      const result = await script.runInContext(sandbox, { timeout: 30000 });
      return { result };
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } catch (error: any) {
      console.error(error);
      return { result: undefined, error: error?.message, logs: [error?.stack] };
    }
  },
};
